site_name: AdWyze Documentation
pages:
- "Getting Started": index.md
- "Latest Updates": updates.md
- Integrations: integrations.md
- Creation: 
- "Quick start": fbcampaigns.md
- "Creation": creation.md
- Rules: rules.md
# - Insights: insights.md
- Preferences: preferences.md
- Troubleshooting: troubleshooting.md
# - Stats: reports.md

# - Billing: billing.md
- Support: support.md
# - "How-to Screencasts": videos.md


theme: cosmo
