site_name: Adwyze Documentation
pages:
- "Getting Started": gettingStarted.md
- "Latest Updates": updates.md
- Integrations: integrations.md
- Campaigns: creation.md
- "Facebook Campaigns": fbcampaigns.md
- Rules: rules.md
- Insights: insights.md
- Troubleshooting: troubleshooting.md
- Stats: reports.md
- Preferences: preferences.md
- Billing: billing.md
- Support: support.md


theme: cosmo
